language: java
addons:
  sonarcloud:
    organization: "alexeybavika"
    token:
      secure: "6a543e97b8f0a9396c5e818e0794d445f02564ac"
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AlexeyBavika_InternetShop

cache:
  directories:
    - $HOME/.m2
