language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "alexeybavika"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AlexeyBavika_InternetShop

cache:
  directories:
    - $HOME/.m2
