language: java
addons:
  sonarcloud:
    organization: "alexeybavika"
    token:
      secure: "4c752579db07769b588e77a20207b4ff60604774"
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AlexeyBavika_InternetShop

cache:
  directories:
    - $HOME/.m2
