language: java
addons:
  sonarcloud:
    organization: "alexeybavika"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - openjdk11
script:
  - mvn verify sonar:sonar

cache:
  directories:
    - $HOME/.m2
