language: java
addons:
  sonarcloud:
    organization: "alexeybavika"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - openjdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - $HOME/.m2
