language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "alexeybavika"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - openjdk11
script:
  - mvn clean install

cache:
  directories:
    - $HOME/.m2
